# Generated by Django 4.2.7 on 2023-11-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMentorBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_input', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CodeDebug',
            fields=[
                ('codementorbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='codementor_ai.codementorbase')),
                ('code_debug', models.JSONField(blank=True, default=dict)),
            ],
            bases=('codementor_ai.codementorbase',),
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('codementorbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='codementor_ai.codementorbase')),
                ('code_review', models.JSONField(blank=True, default=dict)),
            ],
            bases=('codementor_ai.codementorbase',),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('codementorbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='codementor_ai.codementorbase')),
                ('test_case', models.JSONField(blank=True, default=dict)),
            ],
            bases=('codementor_ai.codementorbase',),
        ),
    ]
